// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package initialize

import (
	"github.com/Wafer233/WaferDianPing/wafer-dian-ping-server/internal/application"
	"github.com/Wafer233/WaferDianPing/wafer-dian-ping-server/internal/infrastructure/cache"
	"github.com/Wafer233/WaferDianPing/wafer-dian-ping-server/internal/infrastructure/database"
	"github.com/Wafer233/WaferDianPing/wafer-dian-ping-server/internal/infrastructure/persistence"
	"github.com/Wafer233/WaferDianPing/wafer-dian-ping-server/internal/interfaces/http"
	"github.com/Wafer233/WaferDianPing/wafer-dian-ping-server/internal/interfaces/http/middleware"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func Init() (*gin.Engine, error) {
	db, err := database.NewMysqlDatabase()
	if err != nil {
		return nil, err
	}
	shopTypeRepository := persistence.NewDefaultShopTypeRepository(db)
	shopTypeService := application.NewShopTypeService(shopTypeRepository)
	shopTypeHandler := http.NewShopTypeHandler(shopTypeService)
	userRepository := persistence.NewDefaultUserRepository(db)
	client, err := database.NewRedisDatabase()
	if err != nil {
		return nil, err
	}
	sessionRepository := cache.NewSessionRepository(client)
	sessionService := application.NewSessionService(sessionRepository)
	userService := application.NewUserService(userRepository, sessionService)
	userHandler := http.NewUserHandler(userService)
	blogRepository := persistence.NewDefaultBlogRepository(db)
	blogService := application.NewBlogService(blogRepository, userService)
	blogHandler := http.NewBlogHandler(blogService)
	handlerFunc := middleware.AuthMiddleware(sessionService)
	engine := NewRouter(shopTypeHandler, userHandler, blogHandler, handlerFunc)
	return engine, nil
}
